### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by zibs** [triplecanopy/alongslide-demo#1] opened 2016-08-15 04:54 UTC
Hi all :) 

Not sure what the status is on this project, but I'd love to use it in some forthcoming writings. I'm using it on a Rails 5 project, which aside from a treetop dependency issue, still has the gem bundling + the server running. 

I've paid close attention to the demo and cloned it locally, it works. However, I cannot seem to get it working in the rails 5 version. I've copied pretty much everything over identically and tried to follow as closely along as I could, but maybe I've missed something that isn't obviously spelt out? 

I guess my question is, are there any missing instructions that aren't gleanable from the demo app? 

I can provide some files if you need. Alternatively, could it possibly be a turbolinks issue? (I've tried disabling it, as well as wrapping the JS with a turbolinks:load event). 

Anyways, great work.

**Comment by msimmer** [comment] 2016-08-16 22:50
Hi @zibs,

Thanks for that!

We haven't done much testing for Alongslide on Rails 5, so I'm not really sure what kind of issues might come up there.  

It looks like the issue is likely an [update to jQuery](https://github.com/jquery/jquery/issues/2824) though.  Running Rails 5, I escaped the hashes at line 143 of [alongslide.coffee](https://github.com/triplecanopy/alongslide/blob/master/app/assets/javascripts/alongslide/alongslide.coffee#L143) 

``` coffee
@frames.find('a[href*=\\#]:not([href=\\#])').on('click', (e) ->
```

which sorted things out in case you want to fork the repo and build the gem from there for the time being.

The gem's a bit out of date anyway at this point, so I'll patch it and push a build to rubygems, but I'm not sure when Rails 5 support will come right now.

Would be great to see some Alongslide in the wild, let me know when you get your project underway!

**Comment by zibs** [comment] 2016-08-17 02:50
@msimmer 

Awesome. Thanks for that. I'll let you know how this goes.

**Comment by msimmer** [comment] 2016-09-07 14:40
This is fixed in version [0.9.11](https://rubygems.org/gems/alongslide/versions/0.9.11)

**Closed as completed** 2016-09-07 14:40 UTC

**Comment by zibs** [comment] 2017-10-13 15:24
@msimmer Long time no speak, but I managed to get some basic alongslide sliding on my rails app :D 

Take a looksie here: https://charcuterie.party - and click on any/all of the articles to see it in action.

Thanks for the gem & demo!

**Comment by adamflorin** [comment] 2017-10-13 16:54
@zibs Wow, this is really cool to see, thanks for sharing!! 🙌 

Thanks also @msimmer as ever 😎

**Comment by msimmer** [comment] 2017-10-14 09:00
@zibs nice!!  thanks for the message 😄
